apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
#        git-branch: ${BRANCH_NAME}
#        git-commit: ${SHORT_SHA}
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
      - name: ${APP_NAME}
        image: crpi-8vadjonh2nyqyvih.cn-shanghai.personal.cr.aliyuncs.com/${NAMESPACE}/${APP_NAME}:${IMAGE_TAG}
        ports:
          - containerPort: 8000
        resources:
          requests:
            cpu: "100m"        # 申请1核CPU
            memory: "250Mi"   # 申请4GB内存
          limits:
            cpu: "500m"        # 最大4核CPU
            memory: "1Gi"  # 最大16GB内存