name: Python CI/CD Pipeline

on:
  push:
    branches: ["master"]  # 推送到main分支时触发
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]  # 创建版本时触发发布

permissions:
  contents: read

jobs:
  # 构建和测试作业
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # 指定Python版本

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest  # 安装构建和测试工具

      - name: Run tests
        run: pytest tests/  # 运行单元测试
        env:
          PYTHONPATH: ${{ github.workspace }}/src  # 设置Python路径

      - name: Build source distribution
        run: python -m build --sdist --wheel .  # 生成构建产物

      - name: Install twine for publishing
        run: pip install twine

      - name: Upload to PyPI
        run: twine upload --repository testpypi dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}  # PyPI用户名（需在仓库Secrets中配置）
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # PyPI密码/API Token（需在仓库Secrets中配置）

