name: Python CI/CD Pipeline

on:
  push:
    branches: ["master"]  # 推送到main分支时触发
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]  # 创建版本时触发发布

permissions:
  contents: read

env:
  REGION: cn-shanghai
  ACK_SERVER: ${{ secrets.ACK_CITYARK_SERVER }}
  ACK_CA: ${{ secrets.ACK_CITYARK_CA }}
  ACK_CLIENT_CERTIFICATE: ${{ secrets.ACK_CITYARK_CLIENT_CERTIFICATE }}
  ACK_CLIENT_KEY: ${{ secrets.ACK_CITYARK_CLIENT_KEY }}
  REGISTRY: ${{ secrets.ACR_CITYARK_REGISTRY }}
  NAMESPACE: cityark
  IMAGE_NAME: chromadb
  APP_NAME: chroma-db
  IMAGE_PULL_SECRET: acr-auth

jobs:
  # 构建和测试作业
  build-test-publish:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.set-image-tag.outputs.image_tag }}
      short_sha: ${{ steps.set-image-tag.outputs.short_sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Set short SHA and image tag
#        id: set-image-tag
#        run: |
#          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
#          IMAGE_TAG="${{ github.ref_name }}-$SHORT_SHA"
#          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
#          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT
#          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

#      - name: Set up Python 3.9
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.9  # 指定Python版本
#
#      - name: Install build dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install build pytest versioneer  # 安装构建和测试工具
#          pip install -r requirements.txt # 安装项目依赖
#          versioneer install
#
#      - name: Run tests
#        run: pytest tests/  # 运行单元测试
#        env:
#          PYTHONPATH: ${{ github.workspace }}/src  # 设置Python路径
#
#      - name: Build source distribution
#        run: python setup.py sdist # 生成构建产物
#
#      - name: Install twine for publishing
#        run: pip install twine
#
#      - name: Upload to PyPI
#        run: twine upload --repository testpypi dist/* --verbose
#        env:
#          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # PyPI密码/API Token（需在仓库Secrets中配置）

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_CITYARK_USERNAME }}
          password: ${{ secrets.ACR_CITYARK_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     platforms: linux/amd64
      #     tags: |
      #       ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      # Tekton 镜像同步  
#      - name: Sync Tekton Triggers v0.23.1 images to ACR
#        run: |
#          declare -A IMAGE_MAP=(
#            ["interceptors"]="gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors:v0.23.1"
#          )
#          for NAME in "${!IMAGE_MAP[@]}"; do
#            SRC_IMAGE="${IMAGE_MAP[$NAME]}"
#            DST_IMAGE="${{ env.REGISTRY }}/${{ env.NAMESPACE }}/tektoncd-triggers-${NAME}:v0.23.1"
#            echo "拉取 $SRC_IMAGE"
#            docker pull $SRC_IMAGE
#            echo "推送到 $DST_IMAGE"
#            docker tag $SRC_IMAGE $DST_IMAGE
#            docker push $DST_IMAGE
#          done

      - name: Sync Tekton Task images to ACR
        run: |
          declare -A IMAGE_MAP=(
            ["kaniko-executor"]="gcr.io/kaniko-project/executor:latest"
            ["kubectl"]="bitnami/kubectl:latest"
          )
          for NAME in "${!IMAGE_MAP[@]}"; do
            SRC_IMAGE="${IMAGE_MAP[$NAME]}"
            DST_IMAGE="${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${NAME}:latest"
            echo "拉取 $SRC_IMAGE"
            docker pull $SRC_IMAGE
            echo "推送到 $DST_IMAGE"
            docker tag $SRC_IMAGE $DST_IMAGE
            docker push $DST_IMAGE
          done

#      - name: Configure kubectl
#        uses: azure/setup-kubectl@v3
#        with:
#          version: 'latest'
#
#      - name: Set kubeconfig.yaml
#        run: |
#          mkdir -p ~/.kube
#          envsubst < k8s/kubeconfig.yaml > ~/.kube/config
#
#      - name: Deploy to ACK
#        run: |
#          export IMAGE_TAG=${{ steps.set-image-tag.outputs.image_tag }}
#          export SHORT_SHA=${{ steps.set-image-tag.outputs.short_sha }}
#          envsubst < k8s/template.yaml | kubectl apply -f -
#          kubectl rollout status deployment/${{ env.APP_NAME }} --namespace=${{ env.NAMESPACE }} --timeout=300s
#
